<<<<<<< HEAD
import './globals.css';  // Import global styles
import Header from "../components/Header";

export const metadata = {
  title: 'Mitul’s CP Journey',
  description: 'A collection of resources, tutorials, and guides for competitive programming.',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900">
        <Header />  {/* The Header will be displayed on all pages */}
        <main>{children}</main>  {/* Content of each page */}
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> origin/main
      </body>
    </html>
  );
}
